// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.14.0
// source: deathstar.proto

package service

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DeathstarClient is the client API for Deathstar service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeathstarClient interface {
}

type deathstarClient struct {
	cc grpc.ClientConnInterface
}

func NewDeathstarClient(cc grpc.ClientConnInterface) DeathstarClient {
	return &deathstarClient{cc}
}

// DeathstarServer is the server API for Deathstar service.
// All implementations must embed UnimplementedDeathstarServer
// for forward compatibility
type DeathstarServer interface {
	mustEmbedUnimplementedDeathstarServer()
}

// UnimplementedDeathstarServer must be embedded to have forward compatible implementations.
type UnimplementedDeathstarServer struct {
}

func (UnimplementedDeathstarServer) mustEmbedUnimplementedDeathstarServer() {}

// UnsafeDeathstarServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeathstarServer will
// result in compilation errors.
type UnsafeDeathstarServer interface {
	mustEmbedUnimplementedDeathstarServer()
}

func RegisterDeathstarServer(s grpc.ServiceRegistrar, srv DeathstarServer) {
	s.RegisterService(&Deathstar_ServiceDesc, srv)
}

// Deathstar_ServiceDesc is the grpc.ServiceDesc for Deathstar service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Deathstar_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.deathstar",
	HandlerType: (*DeathstarServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "deathstar.proto",
}
