// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.14.0
// source: destroyer.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DestroyerGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Data  *Data  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DestroyerGetRequest) Reset() {
	*x = DestroyerGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_destroyer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyerGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyerGetRequest) ProtoMessage() {}

func (x *DestroyerGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_destroyer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyerGetRequest.ProtoReflect.Descriptor instead.
func (*DestroyerGetRequest) Descriptor() ([]byte, []int) {
	return file_destroyer_proto_rawDescGZIP(), []int{0}
}

func (x *DestroyerGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DestroyerGetRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *DestroyerGetRequest) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type DestroyerRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Data *Data  `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DestroyerRep) Reset() {
	*x = DestroyerRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_destroyer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyerRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyerRep) ProtoMessage() {}

func (x *DestroyerRep) ProtoReflect() protoreflect.Message {
	mi := &file_destroyer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyerRep.ProtoReflect.Descriptor instead.
func (*DestroyerRep) Descriptor() ([]byte, []int) {
	return file_destroyer_proto_rawDescGZIP(), []int{1}
}

func (x *DestroyerRep) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DestroyerRep) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DestroyerRep) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Infomessage string `protobuf:"bytes,3,opt,name=infomessage,proto3" json:"infomessage,omitempty"`
	Email       string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_destroyer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_destroyer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_destroyer_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetInfomessage() string {
	if x != nil {
		return x.Infomessage
	}
	return ""
}

func (x *Data) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type DestroyerReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dest []*DestroyerRep `protobuf:"bytes,4,rep,name=dest,proto3" json:"dest,omitempty"`
}

func (x *DestroyerReply) Reset() {
	*x = DestroyerReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_destroyer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyerReply) ProtoMessage() {}

func (x *DestroyerReply) ProtoReflect() protoreflect.Message {
	mi := &file_destroyer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyerReply.ProtoReflect.Descriptor instead.
func (*DestroyerReply) Descriptor() ([]byte, []int) {
	return file_destroyer_proto_rawDescGZIP(), []int{3}
}

func (x *DestroyerReply) GetDest() []*DestroyerRep {
	if x != nil {
		return x.Dest
	}
	return nil
}

type TargetFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keyword string `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
}

func (x *TargetFilter) Reset() {
	*x = TargetFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_destroyer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TargetFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetFilter) ProtoMessage() {}

func (x *TargetFilter) ProtoReflect() protoreflect.Message {
	mi := &file_destroyer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetFilter.ProtoReflect.Descriptor instead.
func (*TargetFilter) Descriptor() ([]byte, []int) {
	return file_destroyer_proto_rawDescGZIP(), []int{4}
}

func (x *TargetFilter) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

var File_destroyer_proto protoreflect.FileDescriptor

var file_destroyer_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x64, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x59, 0x0a, 0x13, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79,
	0x65, 0x72, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x12, 0x1c, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x50, 0x0a, 0x0c, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x65, 0x72, 0x52, 0x65, 0x70,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x3e, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x6e,
	0x66, 0x6f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x69, 0x6e, 0x66, 0x6f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x22, 0x36, 0x0a, 0x0e, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x65, 0x72, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x24, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x65,
	0x72, 0x52, 0x65, 0x70, 0x52, 0x04, 0x64, 0x65, 0x73, 0x74, 0x22, 0x28, 0x0a, 0x0c, 0x54, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6b, 0x65,
	0x79, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x65, 0x79,
	0x77, 0x6f, 0x72, 0x64, 0x32, 0x8c, 0x01, 0x0a, 0x09, 0x64, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79,
	0x65, 0x72, 0x12, 0x3f, 0x0a, 0x0e, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x54, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x73, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f,
	0x79, 0x65, 0x72, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e,
	0x70, 0x62, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x0f, 0x6c, 0x69, 0x73, 0x74, 0x54, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x68, 0x73, 0x74, 0x61, 0x72, 0x12, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x1a, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65,
	0x73, 0x74, 0x72, 0x6f, 0x79, 0x65, 0x72, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x00, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x66, 0x72, 0x61, 0x6e, 0x6b, 0x6c, 0x79, 0x6e, 0x6f, 0x62, 0x6c, 0x65, 0x43, 0x2f,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x54, 0x61, 0x73, 0x6b, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_destroyer_proto_rawDescOnce sync.Once
	file_destroyer_proto_rawDescData = file_destroyer_proto_rawDesc
)

func file_destroyer_proto_rawDescGZIP() []byte {
	file_destroyer_proto_rawDescOnce.Do(func() {
		file_destroyer_proto_rawDescData = protoimpl.X.CompressGZIP(file_destroyer_proto_rawDescData)
	})
	return file_destroyer_proto_rawDescData
}

var file_destroyer_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_destroyer_proto_goTypes = []interface{}{
	(*DestroyerGetRequest)(nil), // 0: pb.DestroyerGetRequest
	(*DestroyerRep)(nil),        // 1: pb.DestroyerRep
	(*Data)(nil),                // 2: pb.Data
	(*DestroyerReply)(nil),      // 3: pb.DestroyerReply
	(*TargetFilter)(nil),        // 4: pb.TargetFilter
}
var file_destroyer_proto_depIdxs = []int32{
	2, // 0: pb.DestroyerGetRequest.data:type_name -> pb.Data
	2, // 1: pb.DestroyerRep.data:type_name -> pb.Data
	1, // 2: pb.DestroyerReply.dest:type_name -> pb.DestroyerRep
	0, // 3: pb.destroyer.acquireTargets:input_type -> pb.DestroyerGetRequest
	4, // 4: pb.destroyer.listTargethstar:input_type -> pb.TargetFilter
	3, // 5: pb.destroyer.acquireTargets:output_type -> pb.DestroyerReply
	0, // 6: pb.destroyer.listTargethstar:output_type -> pb.DestroyerGetRequest
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_destroyer_proto_init() }
func file_destroyer_proto_init() {
	if File_destroyer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_destroyer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestroyerGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_destroyer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestroyerRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_destroyer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_destroyer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestroyerReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_destroyer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TargetFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_destroyer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_destroyer_proto_goTypes,
		DependencyIndexes: file_destroyer_proto_depIdxs,
		MessageInfos:      file_destroyer_proto_msgTypes,
	}.Build()
	File_destroyer_proto = out.File
	file_destroyer_proto_rawDesc = nil
	file_destroyer_proto_goTypes = nil
	file_destroyer_proto_depIdxs = nil
}
